baseURL: 'https://delphine-deloof-somatopathe.fr/'

title: 'Delphine De Loof - Somatopathe'
defaultContentLanguage: 'fr'
theme: "hugo-story"
googleAnalytics: "G-P7KWHLFFEQ"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  copyright: "© Delphine De Loof"
  description: "Delphine De Loof - Somatopathe"
  favicon: "images/favicon.png"
  images: ["images/cover-image.jpg"]
  title: "Delphine De Loof - Somatopathe"
  description: "Delphine De Loof - Somatopathe"
  logo: "images/banner.jpg"
  favicon: true
  meta:
    keywords: "somatopathie, delphine deloof"
